# Generated by Django 5.2.7 on 2025-10-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizez', '0002_alter_attempt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the category'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="Icon class name (e.g., 'fas fa-book')", max_length=50),
        ),
    ]
