# Generated by Django 5.2.7 on 2025-10-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizez', '0004_subcategory_answer_is_correct_cached_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='icon',
            field=models.CharField(blank=True, help_text="Icon class (e.g., 'fas fa-book')", max_length=50),
        ),
    ]
