# Generated by Django 5.2.7 on 2025-10-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizez', '0006_quiz_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AddField(
            model_name='answer',
            name='time_taken',
            field=models.PositiveIntegerField(blank=True, help_text='Time taken to answer this question (seconds)', null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='time_taken',
            field=models.PositiveIntegerField(blank=True, help_text='Total time taken in seconds', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer')], default='multiple_choice', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3, help_text='Maximum number of attempts allowed per user'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='passing_score',
            field=models.PositiveIntegerField(default=60, help_text='Passing score percentage'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(default=30, help_text='Time limit in minutes'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt', 'question'], name='Quizez_answ_attempt_eed50d_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['status', 'is_published'], name='Quizez_quiz_status_638f60_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['-created_at'], name='Quizez_quiz_created_c76ed2_idx'),
        ),
    ]
