# Generated by Django 5.2.7 on 2025-11-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizez', '0008_aiquestiondraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiquestiondraft',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Gemini')], default='openai', max_length=20),
        ),
    ]
